GET http://localhost:3000/api/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkBzZXJ2ZXIuY29tIiwicGFzc3dvcmQiOiIyMTIzMmYyOTdhNTdhNWE3NDM4OTRhMGU0YTgwMWZjMyIsIm5hbWUiOiLQkNC00LzQuNC90LjRgdGC0YDQsNGC0L7RgCIsInBob25lIjpudWxsLCJjb21wYW55IjpudWxsLCJjaXR5IjpudWxsLCJyb2xlIjoiYWRtaW4iLCJjcmVhdGVkQXQiOiIyMDIyLTA2LTAzVDA3OjM5OjU1Ljg4N1oiLCJ1cGRhdGVkQXQiOiIyMDIyLTA2LTAzVDA3OjM5OjU1Ljg4N1oiLCJpYXQiOjE2NTQzMjUyMTcsImV4cCI6MTY1NDM2ODQxN30.iKSOPq9nKdc1H_xW1ZQrnj-nHzY7pXgbYr0_U_xDH5A

###

GET http://localhost:3000/api/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYmFzaWMiLCJpZCI6MiwiY2l0eSI6ItCh0YLRgNCw0L3QsCDQt9Cw0LHQstC10L3QuNGPIiwibmFtZSI6ItCY0LLQsNC90L7QsiDQmNCy0LDQvSDQmNCy0LDQvdC-0LLQuNGHIiwicGhvbmUiOiIrNzgwMDU1NTM1MzUiLCJlbWFpbCI6InRlc3QzQG1haWwuY29tIiwiY29tcGFueSI6ItCd0JXQsdGL0LLQsNC70LrQsCIsInBhc3N3b3JkIjoiNWY0ZGNjM2I1YWE3NjVkNjFkODMyN2RlYjg4MmNmOTkiLCJyZWdfZGF0ZSI6IjIwMjItMDQtMTdUMTA6Mjc6MDQuOTkwWiIsInVwZGF0ZWRBdCI6IjIwMjItMDQtMTdUMTA6Mjc6MDQuOTkxWiIsImNyZWF0ZWRBdCI6IjIwMjItMDQtMTdUMTA6Mjc6MDQuOTkxWiIsImlhdCI6MTY1MDE5MTIyNSwiZXhwIjoxNjUwMjM0NDI1fQ.uMsR2QnD4nVOHzSeNFXZsygt68NgHwtsbM7eMWb7YV0


###

GET http://localhost:3000/asdasdas

###

POST http://localhost:3000/api/registration
Content-Type: application/json

{
  "email": "test3@mail.com",
  "password": "password",
  "name": "Иванов Иван Иванович",
  "phone": "+78005553535",
  "company": "НЕбывалка",
  "city": "Страна забвения"
}

###

GET http://localhost:3000/api/login
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYmFzaWMiLCJpZCI6MiwiY2l0eSI6ItCh0YLRgNCw0L3QsCDQt9Cw0LHQstC10L3QuNGPIiwibmFtZSI6ItCY0LLQsNC90L7QsiDQmNCy0LDQvSDQmNCy0LDQvdC-0LLQuNGHIiwicGhvbmUiOiIrNzgwMDU1NTM1MzUiLCJlbWFpbCI6InRlc3QzQG1haWwuY29tIiwiY29tcGFueSI6ItCd0JXQsdGL0LLQsNC70LrQsCIsInBhc3N3b3JkIjoiNWY0ZGNjM2I1YWE3NjVkNjFkODMyN2RlYjg4MmNmOTkiLCJ1cGRhdGVkQXQiOiIyMDIyLTA2LTAzVDA4OjA2OjUxLjQ0MFoiLCJjcmVhdGVkQXQiOiIyMDIyLTA2LTAzVDA4OjA2OjUxLjQ0MFoiLCJpYXQiOjE2NTQyNDM2MTEsImV4cCI6MTY1NDI4NjgxMX0.wjgBBmbxNRG6r92MphfPxIdtDQH4YeqspOIUifsFz5o

###

POST http://localhost:3000/api/login
Content-Type: application/json

{
  "email": "test3@mail.com",
  "password": "password"
}

###


GET  http://localhost:3000/api/logout
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYmFzaWMiLCJpZCI6MiwiY2l0eSI6ItCh0YLRgNCw0L3QsCDQt9Cw0LHQstC10L3QuNGPIiwibmFtZSI6ItCY0LLQsNC90L7QsiDQmNCy0LDQvSDQmNCy0LDQvdC-0LLQuNGHIiwicGhvbmUiOiIrNzgwMDU1NTM1MzUiLCJlbWFpbCI6InRlc3QzQG1haWwuY29tIiwiY29tcGFueSI6ItCd0JXQsdGL0LLQsNC70LrQsCIsInBhc3N3b3JkIjoiNWY0ZGNjM2I1YWE3NjVkNjFkODMyN2RlYjg4MmNmOTkiLCJ1cGRhdGVkQXQiOiIyMDIyLTA2LTAzVDA4OjA2OjUxLjQ0MFoiLCJjcmVhdGVkQXQiOiIyMDIyLTA2LTAzVDA4OjA2OjUxLjQ0MFoiLCJpYXQiOjE2NTQyNDM2MTEsImV4cCI6MTY1NDI4NjgxMX0.wjgBBmbxNRG6r92MphfPxIdtDQH4YeqspOIUifsFz5o

###

POST http://localhost:3000/api/login
Content-Type: application/json

{
  "email": "admin@server.com",
  "password": "admin"
}

###

GET http://localhost:3000/api/user/1

###

POST http://localhost:3000/api/order
Content-Type: application/json

{
  "email": "tes4t3@mail.com",
  "userName": "Иванов Иван Иванович",
  "phone": "+78005553535",
  "company": "НЕбывалка",
  "city": "Страна забвения",
  "type": "documents"
}

###

GET http://localhost:3000/api/orders
Content-Type: application/json


###

###

GET http://localhost:3000/api/documents
Content-Type: application/json


###
