GET http://localhost:3000/api/users

###

GET http://localhost:3000/asdasdas

###

POST http://localhost:3000/api/registration
Content-Type: application/json

{
  "email": "test1@mail.com",
  "password": "password",
  "name": "Иванов Иван Иванович",
  "phone": "+78005553535",
  "company": "НЕбывалка",
  "city": "Страна забвения"
}

###

GET http://localhost:3000/api/login
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiZW1haWwiOiJ0ZXN0MUBtYWlsLmNvbSIsInBhc3N3b3JkIjoiNWY0ZGNjM2I1YWE3NjVkNjFkODMyN2RlYjg4MmNmOTkiLCJuYW1lIjoi0JjQstCw0L3QvtCyINCY0LLQsNC9INCY0LLQsNC90L7QstC40YciLCJwaG9uZSI6Iis3ODAwNTU1MzUzNSIsImNvbXBhbnkiOiLQndCV0LHRi9Cy0LDQu9C60LAiLCJjaXR5Ijoi0KHRgtGA0LDQvdCwINC30LDQsdCy0LXQvdC40Y8iLCJyb2xlIjoiQmFzaWMiLCJyZWdfZGF0ZSI6IjIwMjItMDQtMTZUMDY6MjQ6MzYuMDU3WiIsImNyZWF0ZWRBdCI6IjIwMjItMDQtMTZUMDY6MjQ6MzYuMDU5WiIsInVwZGF0ZWRBdCI6IjIwMjItMDQtMTZUMDY6MjQ6MzYuMDU5WiIsImlhdCI6MTY1MDA5MTgzMywiZXhwIjoxNjUwMTM1MDMzfQ.oJRhbrOSCft-J2-CP-8Ye5qfJFCrFkrkMPY7ndOFIj8

###

POST http://localhost:3000/api/login
Content-Type: application/json

{
  "email": "test1@mail.com",
  "password": "password"
}

###

GET http://localhost:3000/api/user/1
